### ISSUE TITLE
B.关于矩阵快速幂

### ISSUE THREAD

**Issue by Kotagan** [STayinloves/CUGBACM#11]
矩阵的快速幂是用来高效地计算矩阵的高次方的。将朴素的o（n）的时间复杂度，降到log（n）。
这里先对原理（主要运用了矩阵乘法的结合律）做下简单形象的介绍：
一般一个矩阵的n次方，我们会通过连乘n-1次来得到它的n次幂。
但做下简单的改进就能减少连乘的次数，方法如下：
把n个矩阵进行两两分组，比如：AAAAAA => (AA)(AA)(AA)
这样变的好处是，你只需要计算一次AA，然后将结果(AA)连乘自己两次就能得到A^6，即(AA)^3=A^6。算一下发现这次一共乘了3次，少于原来的5次。
其实大家还可以取A^3作为一个基本单位。原理都一样：利用矩阵乘法的结合律，来减少重复计算的次数。
以上都是取一个具体的数来作为最小单位的长度，这样做虽然能够改进效率，但缺陷也是很明显的，取个极限的例子（可能有点不恰当，但基本能说明问题），当n无穷大的时候，你现在所取的长度其实和1没什么区别。所以就需要我们找到一种与n增长速度”相适应“的”单位长度“，那这个长度到底怎么去取呢？？？这点是我们要思考的问题。
有了以上的知识，我们现在再来看看，到底怎么迅速地求得矩阵的N次幂。
既然要减少重复计算，那么就要充分利用现有的计算结果，这里考虑二分的思想。。
计算机处理的是离散的信息，都是以0,1来作为信号的处理的。可想而知二进制在计算机上起着举足轻重的地位。它能将模拟信号转化成数字信号，将原来连续的实际模型，用一个离散的算法模型来解决。
回头看看矩阵的快速幂问题，我们是不是也能把它离散化呢？比如A^19 => （A^16）（A^2）（A^1），显然采取这样的方式计算时因子数将是log(n)级别的(原来的因子数是n)，不仅这样，因子间也是存在某种联系的，比如A^4能通过(A^2)(A^2)得到，A^8又能通过(A^4)*(A^4)得到，这点也充分利用了现有的结果作为有利条件。

**Comment by sanxing-chen** [comment]
Add to #5 , closed.
