### ISSUE TITLE
A. Fate（HDU2159）

### ISSUE THREAD

**Issue by MFunction96** [STayinloves/CUGBACM#3]
## 原题链接：

> http://acm.hdu.edu.cn/showproblem.php?pid=2159

## 描述
最近xhd正在玩一款叫做FATE的游戏，为了得到极品装备，xhd在不停的杀怪做任务。久而久之xhd开始对杀怪产生的厌恶感，但又不得不通过杀怪来升完这最后一级。现在的问题是，xhd升掉最后一级还需`n`的经验值，xhd还留有`m`的忍耐度，每杀一个怪xhd会得到相应的经验，并减掉相应的忍耐度。当忍耐度降到`0`或者`0`以下时，xhd就不会玩这游戏。xhd还说了他最多只杀`s`只怪。请问他能升掉这最后一级吗？
## 输入
输入数据有多组，对于每组数据第一行输入`n,m,k,s(0<n,m,k,s<100)`四个正整数。分别表示还需的经验值，保留的忍耐度，怪的种数和最多的杀怪数。接下来输入`k`行数据。每行数据输入两个正整数`a,b(0<a,b<20)`；分别表示杀掉一只这种怪xhd会得到的经验值和会减掉的忍耐度。(每种怪都有无数个)
## 输出
输出升完这级还能保留的最大忍耐度，如果无法升完这级输出`-1`。
## 样例输入
10 10 1 10
1 1
10 10 1 9
1 1
9 10 2 10
1 1
2 2
## 样例输出
0
-1
1
## 解题思路
首先根据题意判断该题为完全背包问题。
完全背包问题需要使用动态规划解。
首先分析题干中的有关完全背包问题的限制信息：差`n`点经验升级，武器共有`m`点耐久，最多使用`s`次武器——背包大小为`m`，要求装入价值不低于`n`的物品，另外最多装入`s`个物品。其次确定动态规划限制条件，动态规划限制条件三选二，剩下的一个作为判断即可。最后根据确定的条件找出状态转移方程。
## Accepted代码
由于题目要求计算武器剩余的最大耐久度，因此设动态规划的限制条件为经验值、武器使用次数，判断条件选择武器耐久度。
将初始状态的dp数组初始化为`-1`表示未标记状态，并设置初始状态。由初始状态进行状态转移，当新状态的武器耐久度大于当前状态的武器耐久度（包括该新状态处于未标记状态）时，更新新状态的武器耐久度，以此类推进行状态更新。更新终点为当状态的不满足任意一个限制条件时终止更新。
``` c++
#include<cstdio>
#include<cstring>
#include<vector>
#include<algorithm>
using namespace std;

const int MAXN = 100 + 50;
const int INF = 0x7fffffff;

struct monster
{
	int exp, cost;
	monster(int e, int c) :exp(e), cost(c) {}					//声明及定义结构体构造函数
};

int dp[MAXN][MAXN];
vector<monster> v;									//使用容器存储结构体

int main()
{
	int n, m, k, s, e, c, ans, x, y, i;
	while (scanf("%d%d%d%d", &n, &m, &k, &s) == 4)
	{
		v.clear();								//初始化容器
		memset(dp, -1, sizeof(dp));						//初始化dp数组
		ans = -1;								//将最终结果储存为负无穷
		while (k--)
		{
			scanf("%d%d", &e, &c);
			v.push_back(monster(e, c));					//容器中添加怪物类型
		}
		dp[n][s] = m;								//初始化状态
		for (y = n; y >= 0; y--)						//遍历所有经验状态
		{
			for (x = s; x > 0; x--)						//遍历所有杀怪数量
			{
				if (dp[y][x] >= 0)					//判断当前状态是否有效
				{
					for (i = 0; i < v.size(); i++)
					{
						if (dp[y][x] - v[i].cost >= 0)		//当新状态满足状态更新条件
						{
							//当新状态满足状态终止条件时更新最终结果
							if (y - v[i].exp <= 0) ans = max(ans, dp[y][x] - v[i].cost);
							//当新状态仅满足状态更新条件时仅更新状态
							else dp[y - v[i].exp][x - 1] = max(dp[y][x] - v[i].cost, dp[y - v[i].exp][x - 1]);
						}
					}
				}
			}
		}
		printf("%d\n", ans);							//输出最终结果
	}
	return 0;
}
```

**Comment by sanxing-chen** [comment]
6666，[这篇文章](http://mindhacks.cn/2010/11/14/the-importance-of-knowing-why-part2/)里把背包问题分析得很透彻，不熟悉的同学可以看看
