### ISSUE TITLE
D. Science!!

### ISSUE THREAD

**Issue by ybai-nlp** [STayinloves/CUGBACM#7]
# Science!
Time Limit: 5000/2000 MS (Java/Others)    Memory Limit: 32768/32768 K (Java/Others)
Total Submission(s): 415    Accepted Submission(s): 116
Special Judge

## Problem Description
Welcome, ladies and gentlemen, to Aperture Science. Astronauts, War Heroes, Olympians — you’re here because we want the best, and you are it. That said, it’s time to make some science.
Now, I want each of you to stand on one of these buttons. Well done, we’re making great progress here. Now let’s do it again. Oh, come on - don’t stand on the same button! Move, people! No, no, that button’s only for the Astronauts, you know who you are. What?! You say you can’t do everything I ask? Ok let’s start over. You there, the Programmer, figure out how many times we can do this. And make it quick, we have a lot more science to get through…
 

## Input
There will be several test cases in the input. The first line of each case will contain n (2≤n≤80) giving the number of people (and the number of buttons) in the experiment. The next n lines will contain n characters each. If the jth character of the ith line is Y it indicates that the ith person can stand on the jthbutton (it is N otherwise). The last line of input will be a 0.
 

## Output
For each test case, output k, the maximum number of times everyone can be standing on buttons such that nobody stands on the same button more than once (This might be 0). After that, output k lines. Each line should contain n integers separated by single spaces, where the ith integer describes which person is standing on the ith button. All of the lines should be valid and none of them should put the same person on the same button as a previous line of the same test case. Output no extra spaces, and do not separate answers with blank lines. Note that correct outputs might not be unique.

## **Sample Input**
3
YYY
NYY
YNY
2
YN
YN
0
## **Sample Output**
2
3 1 2
1 2 3
0
 
这道题题意很简单，有n个人和n个位置，这n个人站队。每个人都只能进入特定的某几个位置，并且一个人如果站过一个位置之后，他在其他的队形中就不能还在这个位置。问一共能够站成多少种不同的队形。并将每种不同的队形输出来。

一开始考虑做一个二分图，求完美匹配数，用匈牙利算法验证能否完美匹配，每匹配一次就将相应的边删除掉。然而这种方法只能求出完美匹配的数目，并不能求出每次匹配各点的连接情况，之后在网上搜题解，题解解释的太抽象，给出的代码又是又臭又长，没有注释，很难理解。尤其是有一步二分法找答案，百思不得其解。然后我们就去问张雯慧学姐，在学姐的指导下我们去看了HDU3081这道题，题意如下：有N个女孩要与N个男孩玩配对游戏.每个女孩有一个可选男孩的集合(即该女孩可以选自己集合中的任意一个男孩作为该轮的搭档).然后从第一轮开始,每个女孩都要和一个不同的男孩配对.如果第一轮N个女孩都配对成功,那么就开始第二轮配对,女孩依然从自己的备选男孩集合中选择,但是不能选那些已经被该女孩在前几轮选择中选过的男孩了(比如i女孩在第一轮选了j男孩,那么i在第二轮就不能选j男孩了). 问你游戏最多能进行多少轮?其实就是简化版的HDU4265，即只需求完美匹配数目。这道题给出了两种解决方法且题解比较详细，第一种方法即使用二分图，而第二种方法则是使用了刚刚提到的二分最大流算法。

我们假设一个超级源点S为0，超级汇点为2*n+1，人们的编号是1到n，位置的编号为n+1到2*n，假设尝试的轮数为K（即能够进行K轮匹配）：

如果第i个人可以到第j个位置，那么建边（i，j+n，1），设源点到人们和位置到汇点之间都有边长为K的边，如果从源点到汇点的最大流==K*n，就表示可以进行最少K轮匹配，而从一开始的第一个不满足最大流等于K*n的点，即为所求最大匹配数。

为什么这个结论是正确的呢？首先我们假设当前图中没有人走入自己的位置，即人与位置之间的边流量为零，我们从源点流出流量n，分别流到这n个人身上，每个人分得流量1。由于人和位置之间的每条边的流量均为1，若能进行完美匹配，这n个流量最终都将流入汇点，即汇点接收流量n。这时我们在源点再次流出流量n，由于第一次匹配时已经有一些边中有流量了，所以这些边将不能再流通，即对于不同的队形，每个人都不会站到之前自己站过的位置。最终汇点将接收到流量2*n，以此类推，如果接下来的每次流出都能在汇点接收到全部流量，即最大流等于K*n时，至少可以进行这K轮匹配。

接下来的问题就是如何求出这些不同的状态了，先把没有关系的边删除，然后找k次，每次跑一边网络流，s到每个点的容量为1，这样就可以保证残留网络中有一组解，然后，输出这些解，然后删掉这一组解所对应的边。

详见代码。

``` c++
#include<iostream>
#include<cstring>
#include<cstdio>
#include<queue>
#define inf 0x7fffffff
using namespace std;
const int nodes=200;
const int edges=40000+50;
int n,s,t;
struct node
{
    int v,next,flow;
}e[edges];  //建立邻接表
int head[nodes],cur[nodes],cnt;
char map[nodes][nodes];
class Dinic
{
    public:
        int spath()  //spfa求最短路径
        {
            queue<int>q;
            while(!q.empty()) q.pop();
            memset(dis,-1,sizeof(dis));
            dis[s]=0;
            q.push(s);
            while(!q.empty())
            {
                int u=q.front();
                q.pop();
                for(int i=head[u];i+1;i=e[i].next)
                {
                    int v=e[i].v;
                    if(dis[v]==-1&&e[i].flow>0)
                    {
                        dis[v]=dis[u]+1;
                        q.push(v);
                    }
                }
            }
            return dis[t]!=-1;
        }
        int Min(int a,int b)
        {
            if(a<b) return a;
            return b;
        }
        int dfs(int u,int flow)
        {
            int cost=0;
            if(u==t) return flow;
            for(int &i=cur[u];i+1;i=e[i].next)
            {
                //cur[u]=i;
                int v=e[i].v;
                if(dis[v]==dis[u]+1&&e[i].flow>0)
                {
                    int minn=dfs(v,Min(e[i].flow,flow-cost));
                    if(minn>0)
                    {
                        e[i].flow-=minn;
                        e[i^1].flow+=minn;
                        cost+=minn;
                        if(cost==flow) break;
                    }
                    else dis[v]=-1;
                }
            }
            return cost;
        }
        int result()
        {
            int xx=0;
            while(spath())
            {
                for(int i=s;i<=t;i++) cur[i]=head[i];
                xx+=dfs(s,inf);
            }
            return xx;
        }
    private:
        int dis[nodes];
}dinic;
void Init()
{
    memset(head,-1,sizeof(head));
    cnt=0;
}
void add(int a,int b,int c)
{
    e[cnt].v=b;
    e[cnt].next=head[a];
    e[cnt].flow=c;
    head[a]=cnt++;

    e[cnt].v=a;
    e[cnt].flow=0;
    e[cnt].next=head[b];
    head[b]=cnt++;
}
void build_map(int val) //建一个虚拟起点和终点与点之间距离为val的图
{
    Init();
    for(int i=1;i<=n;i++)
    {
        add(s,i,val);
        add(i+n,t,val);
    }
    for(int i=1;i<=n;i++)
    {
        for(int j=1;j<=n;j++)
        {
            if(map[i][j]=='Y')
            {
                add(i,j+n,1);
            }
        }
    }
}
int find_mid()  //查找最大匹配数，即为各自不同的站法
{
    int low=0,up=n,ans=0;
    while(low<=up)
    {
        int mid=(low+up)>>1;
        build_map(mid);//建一个mid图
        if(dinic.result()==mid*n)
        {
            ans=mid;
            low=mid+1;  //因为要找最大的匹配次数
        }
        else up=mid-1;
    }
    return ans;
}
void find_one_ans_del()
{
    int res[nodes];
    for(int i=1;i<=n;i++)//仍未确认这一个循环的必要性
    {
        for(int j=head[i];j+1;j=e[j].next)
        {
            int v=e[j].v;
            if(v!=s&&!e[j].flow)
            {
                res[v-n]=i;
                map[i][v-n]='N';
                break;//剪枝
            }
        }
    }
    for(int i=1;i<=n;i++)
    {
        if(i==1) printf("%d",res[i]);
        else printf(" %d",res[i]);
    }
    printf("\n");
    /*for(int i=1;i<=n;i++)
    {
        for(int j=head[i];j+1;j=e[j].next)
        {
            int v=e[j].v;
            if(v!=s&&e[j].flow==0)
            {
                map[i][v-n]='N';
                break;
            }
        }
    }*/
}
void treatment(int rmid) //确定每一种情况的具体站位
{
    printf("%d\n",rmid);//s输出最大完美匹配数
    build_map(rmid);  //建图
    dinic.result();   //求最大流
    for(int i=1;i<=n;i++)
    {
        for(int j=head[i];j+1;j=e[j].next)
        {
            int v=e[j].v;
            if(v!=s&&e[j].flow==1)
            {
                map[i][v-n]='N';
            }
        }
    }
    while(rmid--)
    {
        build_map(1);//建一个k=1的图
        dinic.result();
        find_one_ans_del();//找到具体的位置信息
    }
}
int main()
{
    while(~scanf("%d",&n),n)
    {
        for(int i=1;i<=n;i++)
        {
            scanf("%s",map[i]+1);
        }
        s=0;t=2*n+1;
        int kr=find_mid();
        treatment(kr);
    }
    return 0;
}
```

**Comment by ybai-nlp** [comment]
啦啦啦

**Comment by sanxing-chen** [comment]
帮你把格式调了一下，可以看看语法
